spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Use 'update' during development, 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  jackson:
    serialization:
      fail-on-empty-beans: false

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

#google:
#  maps:
#    api-key: ${env.GOOGLE_MAPS_API_KEY}

server:
  port: 8080
  servlet:
    context-path: /api

# Logging
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.aegis: DEBUG

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha